In [1]:
import pandas as pd # pd é o nome da biblioteca
                    # pandas é uma biblioteca dopython para analise de dados,...
                    # ... maniupulação de tabelas, limpeza de dados e leitura de arquivos (csv, excel)

import numpy as np # numpy é uma biblioteca para computação numérica

# .ipynb serve para rodar os códigos separados por células, é o formato do jupyter notebook
# sempre que ligar o pc novamente, rodar todos os códigos no "run all"

In [2]:
dados = "https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv"
df = pd.read_csv(dados, encoding= "latin1", sep= ";") # df = dataframe (estrutura de dados em tabelas)
                                                      # read_csv() faz ler o arquivo em formato de tabelas
                                                      # pd é o nome da biblioteca utilizada
                                                      # dados é para citar a variavel utilizada
                                                      # encoding= é para "traduzir" para a versão do windows
                                                      # sep= ";" informa o separador do arquivo

display(df.head()) # display() mostra em formato de tabela, mas não tem a necessidade de escrever
                   # df.head() mostra só as primeiras 5 (ou a quantidade que colocar entre os parenteses) linhas de um dataframe (tabela) 
                   # df.tail() mostra as 5 ultimas linhas

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [3]:
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index() # .groupby é para agrupar o que for mencionado (cisp)
                                                                                # (cisp) executa o agroupby
                                                                                # [furto_celular] mostra a coluna que será mencionada
                                                                                # sum() para somar o que foi mencionado
                                                                                # .reset_index() é para refazer uma nova tabela mencionado no df 
                                                                                # ... no início do código
                                                                                # cisp é uma das colunas do arquivo mencionado

df_furto_celular_cisp       # df_furto_celular_cisp é para mostrar a tabela após os códigos acima

     cisp  furto_celular
0       1          15487
1       4          13700
2       5          23969
3       6           6410
4       7           1485
..    ...            ...
133   159            455
134   165           1233
135   166           2580
136   167            497
137   168            121

[138 rows x 2 columns]

In [4]:
df.describe() # pega as colunas com dados numericos

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,3.731400e+04,37314.000000,37314.000000,37314.000000,37314.000000,...,32668.000000,32668.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000
mean,81.724259,6.482232,2014.188723,20.148470,3.869942,3.791939e+06,2.925256,0.028140,0.095380,3.048775,...,8.741306,0.641545,41.308731,3.223964,0.360481,0.022967,0.013400,0.002224,444.005306,2.985314
std,48.320410,3.461767,6.625316,11.348509,2.011450,1.741132e+06,4.327953,0.179516,0.366265,4.443058,...,14.809300,1.640367,39.390699,4.160668,0.988235,0.181215,0.130895,0.049334,398.542615,0.120295
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2008.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,370.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,663.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [5]:
df.shape # quantidade de linhas e quantidades de colunas

(37314, 65)

In [6]:
df.columns # mostra o nome de todas as colunas

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [7]:
df.iloc[0:5] # menciona as linhas quer mostrar para o usuário 0:5 = primeira linha a quinta linha

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [8]:
df.loc[df['munic'] == 'Rio de Janeiro'] # df.loc é para filtrar entre colchetes []
                                        # [df['muic']... informa qual coluna é para aparecer no dataframe

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37213,40,1,2026,2026m01,9,2,Rio de Janeiro,3304557,Capital,3,...,3.0,2.0,38,5,1,0,0,0,689,2
37214,41,1,2026,2026m01,18,2,Rio de Janeiro,3304557,Capital,2,...,5.0,0.0,37,3,1,0,0,0,858,2
37215,42,1,2026,2026m01,31,2,Rio de Janeiro,3304557,Capital,2,...,15.0,6.0,113,7,0,0,0,0,1444,2
37216,43,1,2026,2026m01,27,2,Rio de Janeiro,3304557,Capital,0,...,3.0,0.0,103,11,0,0,0,0,645,2
37217,44,1,2026,2026m01,3,1,Rio de Janeiro,3304557,Capital,1,...,12.0,0.0,32,3,0,0,0,0,853,2

In [9]:
df_2024 = df.loc[df['ano'] == 2024]
df_pessoas_desaparecidas_2024 = df_2024.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index() # df_2024 é a nova tabela que foi criada com
                                                                                                        # ... código acima 
df_pessoas_desaparecidas_2024

     cisp  pessoas_desaparecidas
0       1                     14
1       4                     50
2       5                     55
3       6                     34
4       7                     18
..    ...                    ...
132   159                     17
133   165                     12
134   166                     60
135   167                     14
136   168                      4

[137 rows x 2 columns]

In [10]:
df_baixada_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Baixada Fluminense')] # cada filtro fica dentro de um "[(df[...] == ...)..." e separados por "&"
                                                                                       # ... após o "loc"
df_baixada_2020

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
27354,48,1,2020,2020m01,24,3,Seropédica,3305554,Baixada Fluminense,2,...,10.0,0.0,30,2,0,0,0,0,259,3
27355,50,1,2020,2020m01,24,3,Itaguaí,3302007,Baixada Fluminense,1,...,9.0,0.0,42,1,0,0,0,0,376,3
27356,51,1,2020,2020m01,24,3,Paracambi,3303609,Baixada Fluminense,0,...,6.0,0.0,16,0,0,0,0,0,116,3
27357,52,1,2020,2020m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,24.0,1.0,42,5,0,0,0,0,860,3
27358,53,1,2020,2020m01,20,3,Mesquita,3302858,Baixada Fluminense,3,...,11.0,0.0,57,7,1,0,0,0,610,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28875,63,12,2020,2020m12,24,3,Japeri,3302270,Baixada Fluminense,5,...,2.0,2.0,15,1,0,0,0,0,152,3
28876,64,12,2020,2020m12,21,3,São João de Meriti,3305109,Baixada Fluminense,13,...,8.0,0.0,85,10,0,0,0,0,1189,3
28877,65,12,2020,2020m12,34,3,Magé,3302502,Baixada Fluminense,3,...,6.0,0.0,23,1,0,0,0,0,197,3
28878,66,12,2020,2020m12,34,3,Magé,3302502,Baixada Fluminense,0,...,7.0,1.0,65,8,0,0,0,0,390,3
28879,67,12,2020,2020m12,34,3,Guapimirim,3301850,Baixada Fluminense,1,...,1.0,0.0,13,1,0,0,0,0,114,3

In [11]:
dados = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40]) # Criei uma lista, porém, poderia ser uma já existente
                                                           # array é uma estrutura que guarda varios elementos iguais (q1 q2 q3)
q1 = np.percentile(dados, 25) # 25% da lista # .percentile() coloca o em porcentagem
q2 = np.percentile(dados, 50) # 50% da lista # .percentile() coloca o em porcentagem
q3 = np.percentile(dados, 75) # 75% da lista # .percentile() coloca o em porcentagem
print(f'Primeiro quartril (Q1): {q1}')
print(f'Segundo quartril (Q2): {q2}')
print(f'Terceiro quartril (Q3): {q3}')

Primeiro quartril (Q1): 17.75
Segundo quartril (Q2): 23.5
Terceiro quartril (Q3): 29.5

In [25]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])
q1_furto_celular = np.percentile(array_furto_celular, 25) # array transforma uma lista voltada para cálculos específicos
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media = np.mean(array_furto_celular) 
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
iqr = q3_furto_celular - q1_furto_celular
limite_superior = q3_furto_celular + (1.5 * iqr)
limite_inferior = q1_furto_celular - (1.5 * iqr)


print(f'Primeiro quartril (Q1): {q1_furto_celular}')
print(f'Segundo quartril (Q2): {q2_furto_celular}')
print(f'Terceiro quartril (Q3): {q3_furto_celular}')
print(f'O valor da média é {media}')
print(f'O valor da mediana é {mediana}')
print(f'A distância entre média e mediana é {distancia}')
print(f'O limite superior é de {limite_superior}')
print(f'O limite inferior é de {limite_inferior}')

Primeiro quartril (Q1): 451.25
Segundo quartril (Q2): 1675.5
Terceiro quartril (Q3): 4580.0
O valor da média é 3422.978260869565
O valor da mediana é 1675.5
A distância entre média e mediana é 1.042959272378135
O limite superior é de 10773.125
O limite inferior é de -5741.875

In [ ]:
# Identificar o que puxa a media para cima (outiliers)

outiliers_cisp_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] >= limite_superior]
outiliers_cisp_furto_celular = outiliers_cisp_furto_celular.sort_values(by='furto_celular', ascending=False)
outiliers_cisp_furto_celular

    cisp  furto_celular
12    16          25480
2      5          23969
10    14          17633
8     12          16659
0      1          15487
5      9          14621
6     10          14370
14    18          13808
1      4          13700
28    32          12504
31    35          12007

In [13]:
df_menor_q1_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]

df_menor_q1_furto_celular = df_menor_q1_furto_celular.sort_values(by='furto_celular', ascending= False) # ascending= False é para colocar do maior para o menor
                                                                                                        # by= '   ' indica por qual coluna o usuário quer ordenar

df_menor_q1_furto_celular

     cisp  furto_celular
99    121            450
90    107            446
84     99            435
85    100            401
7      11            392
60     67            372
79     94            367
115   139            364
86    101            356
111   135            355
113   137            303
98    120            299
127   153            254
108   130            242
82     97            233
95    112            211
61     70            202
100   122            202
124   148            195
116   140            165
123   147            165
132   158            154
92    109            143
118   142            128
137   168            121
126   152            109
130   156            109
83     98             90
94    111             82
41     45             73
87    104             72
77     92             65
131   157             55
114   138             53
129   155             47

In [14]:
df_capital_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Capital')]
df_capital_2020

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
27313,1,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,1.0,8,0,0,0,0,0,665,3
27314,4,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,1,...,15.0,13.0,10,3,0,0,0,0,600,3
27315,5,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,12.0,7.0,32,1,0,0,0,0,1193,3
27316,6,1,2020,2020m01,4,1,Rio de Janeiro,3304557,Capital,1,...,5.0,4.0,22,2,0,0,0,0,480,3
27317,7,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,1.0,1.0,10,0,0,0,0,0,161,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28856,40,12,2020,2020m12,9,2,Rio de Janeiro,3304557,Capital,2,...,3.0,0.0,22,2,0,0,0,0,420,3
28857,41,12,2020,2020m12,18,2,Rio de Janeiro,3304557,Capital,1,...,4.0,0.0,47,6,0,0,0,0,391,3
28858,42,12,2020,2020m12,31,2,Rio de Janeiro,3304557,Capital,0,...,8.0,1.0,81,2,0,0,0,0,745,3
28859,43,12,2020,2020m12,27,2,Rio de Janeiro,3304557,Capital,5,...,2.0,0.0,69,3,0,0,0,0,394,3
28860,44,12,2020,2020m12,3,1,Rio de Janeiro,3304557,Capital,2,...,25.0,0.0,19,2,1,0,0,0,487,3

In [15]:
df_menores_capital_2020 = df_capital_2020.groupby('cisp')['aaapai'].sum().reset_index()
df_menores_capital_2020 = df_menores_capital_2020.sort_values(by='aaapai', ascending= False)
df_menores_capital_2020

    cisp  aaapai
10    14   170.0
12    16   143.0
8     12   136.0
33    37   104.0
9     13   104.0
29    33    67.0
6     10    66.0
28    32    64.0
2      5    61.0
31    35    45.0
35    39    43.0
30    34    41.0
5      9    37.0
1      4    34.0
27    31    32.0
3      6    32.0
23    27    29.0
17    21    29.0
15    19    28.0
34    38    26.0
0      1    25.0
38    42    25.0
13    17    24.0
36    40    22.0
25    29    21.0
19    23    19.0
40    44    19.0
26    30    18.0
18    22    18.0
21    25    18.0
22    26    18.0
20    24    17.0
16    20    15.0
11    15    12.0
37    41    12.0
4      7    10.0
32    36     7.0
24    28     7.0
14    18     4.0
39    43     3.0
7     11     0.0

In [16]:
gestao_atual = [2023,2024,2025,2026]
df_interior_atual = df.loc[(df['regiao'] == 'Interior') & (df['ano']).isin(gestao_atual)] # .isin(nome da variável) busca dentro da variavel 
df_interior_atual

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
32305,70,1,2023,2023m01,35,4,Tanguá,3305752,Interior,0,...,3.0,0.0,8,0,0,0,0,0,68,3
32306,71,1,2023,2023m01,35,4,Itaboraí,3301900,Interior,1,...,6.0,0.0,26,2,0,0,0,0,454,3
32317,88,1,2023,2023m01,10,5,Barra do Pirai,3300308,Interior,2,...,8.0,0.0,22,1,0,0,0,0,261,3
32318,89,1,2023,2023m01,37,5,Resende,3304201,Interior,6,...,10.0,2.0,37,4,0,0,0,0,516,3
32319,90,1,2023,2023m01,28,5,Barra Mansa,3300407,Interior,6,...,8.0,0.0,61,0,0,0,0,0,480,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [17]:
regiao_metropolitana = ['Belford Roxo', 'Cachoeiras de Macacu', 'Duque de Caxias', 'Guapimirim', 'Itaboraí', 'Itaguaí', 'Japeri', 'Magé', 'Maricá', 'Mesquita','Nilópolis', 'Niterói',
                        'Nova Iguaçu', 'Paracambi', 'Petrópolis', 'Queimados', 'Rio Bonito', 'Rio de Janeiro', 'São Gonçalo', 'São João de Meriti', 'Seropédica', 'Tanguá']
df_metropolitana_2024 = df.loc[(df['munic'].isin(regiao_metropolitana) & (df['ano'] == 2024))]
df_metropolitana_2024

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
33889,1,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,16.0,4.0,12,0,0,0,0,0,889,3
33890,4,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,8.0,6.0,13,3,0,0,0,0,728,3
33891,5,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,12.0,2.0,46,3,0,0,0,0,1441,3
33892,6,1,2024,2024m01,4,1,Rio de Janeiro,3304557,Capital,0,...,2.0,1.0,23,2,0,0,0,0,650,3
33893,7,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,0.0,12,2,0,0,0,0,240,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35467,82,12,2024,2024m12,12,4,Maricá,3302700,Grande Niterói,2,...,11.0,0.0,115,5,0,0,0,0,1076,3
35483,105,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,11.0,0.0,75,3,0,0,0,0,782,3
35484,106,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,7.0,1.0,42,3,0,0,0,0,354,3
35492,119,12,2024,2024m12,35,4,Rio Bonito,3304300,Interior,0,...,0.0,0.0,20,0,0,0,0,0,178,3
35528,159,12,2024,2024m12,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,1.0,0.0,27,2,0,0,0,0,137,3

In [18]:
df_furto_celular_rm_24 = df_metropolitana_2024.groupby('cisp')['furto_celular'].sum().reset_index()

array_furto_celular = np.array(df_metropolitana_2024['furto_celular'])
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
print(f'O valor da média é {media}')
print(f'O valor da mediana é {mediana}')
print(f'A distância entre média e mediana é {distancia}')

O valor da média é 37.838815789473685
O valor da mediana é 18.0
A distância entre média e mediana é 1.102156432748538

In [19]:
munic = df.groupby('munic').size().reset_index(name='Quantidade')
munic

                 munic  Quantidade
0       Angra dos Reis         277
1             Araruama         277
2   Armação dos Búzios         277
3      Arraial do Cabo         181
4          Barra Mansa         277
..                 ...         ...
85         Teresópolis         277
86   Trajano de Morais         277
87             Valença         277
88           Vassouras         277
89       Volta Redonda         277

[90 rows x 2 columns]

In [27]:
munic.to_csv('Municipios_csv', index=False, sep= ';') # .to_csv() cria um arquivo para visualização completa
                                                      # index=False para não implicar no código atual

In [63]:
df_ocorrencias_veiculos = df.groupby('cisp')[['roubo_veiculo', 'furto_veiculos']].sum().reset_index()
df_ocorrencias_veiculos = df_ocorrencias_veiculos.sort_values(by='roubo_veiculo')
df_ocorrencias_veiculos

     cisp  roubo_veiculo  furto_veiculos
114   138              2              24
113   137              6             131
116   140              7             190
115   139              7              75
118   142              9             104
..    ...            ...             ...
30     34          27298            9804
23     27          27543           11907
35     39          29077            3868
57     64          32360           11613
52     59          37271           14753

[138 rows x 3 columns]

In [64]:
df_ocorrencias_veiculos['total_ocorrencias'] = df_ocorrencias_veiculos['roubo_veiculo'] + df_ocorrencias_veiculos['furto_veiculos']
df_ocorrencias_veiculos

     cisp  roubo_veiculo  furto_veiculos  total_ocorrencias
114   138              2              24                 26
113   137              6             131                137
116   140              7             190                197
115   139              7              75                 82
118   142              9             104                113
..    ...            ...             ...                ...
30     34          27298            9804              37102
23     27          27543           11907              39450
35     39          29077            3868              32945
57     64          32360           11613              43973
52     59          37271           14753              52024

[138 rows x 4 columns]

In [69]:
array_ocorrencia = np.array(df_ocorrencias_veiculos[['total_ocorrencias']])
q1_roubo_veiculos = np.percentile(array_ocorrencia, 25)
q2_roubo_veiculos = np.percentile(array_ocorrencia, 50)
q3_roubo_veiculos = np.percentile(array_ocorrencia, 75)
media_ocorrencia = np.mean(array_ocorrencia)
mediana_ocorrencia = np.median(array_ocorrencia)
distancia_ocorrencia = (media_ocorrencia - mediana_ocorrencia) / mediana_ocorrencia
iqr = q3_furto_celular - q1_furto_celular
limite_superior = q3_furto_celular + (1.5 * iqr)
limite_inferior = q1_furto_celular - (1.5 * iqr)

print(f'O terceiro quatril é de {q3_roubo_veiculos}')
print(f'O limite superior é de {limite_superior}')
print(f'O limite inferior é de {limite_inferior}')

O terceiro quatril é de 12801.75
O limite superior é de 10773.125
O limite inferior é de -5741.875

In [71]:
outiliers_cisp_ocorrencias_veiculo = df_ocorrencias_veiculos.loc[df_ocorrencias_veiculos['total_ocorrencias'] >= limite_superior]
outiliers_cisp_ocorrencias_veiculo = outiliers_cisp_ocorrencias_veiculo.sort_values(by='total_ocorrencias', ascending=False)
outiliers_cisp_ocorrencias_veiculo

    cisp  roubo_veiculo  furto_veiculos  total_ocorrencias
52    59          37271           14753              52024
57    64          32360           11613              43973
23    27          27543           11907              39450
30    34          27298            9804              37102
31    35          19186           14538              33724
35    39          29077            3868              32945
47    54          24620            7793              32413
34    38          19774            6523              26297
29    33          17862            8263              26125
45    52          15443           10614              26057
53    60          20278            5414              25692
17    21          19604            5982              25586
65    74          18002            7405              25407
18    22          15072            8027              23099
63    72          13934            9045              22979
36    40          19082            3684              22766
51    58          16098            6460              22558
25    29          16305            5924              22229
64    73          13860            6177              20037
12    16           5864           12447              18311
26    30          12660            5378              18038
27    31          14866            3057              17923
50    57          12450            5056              17506
40    44          14619            2784              17403
49    56          11833            3694              15527
19    23          10743            4619              15362
20    24          11842            3034              14876
24    28          10939            3585              14524
28    32           8412            5787              14199
69    78           8513            5192              13705
16    20           9023            4335              13358
33    37           7355            5646              13001
46    53           8442            4473              12915
5      9           4669            8160              12829
21    25          10952            1868              12820
68    77           4132            8615              12747
62    71           8094            4492              12586
66    75           9969            2389              12358
55    62           9076            2512              11588
13    17           7662            3769              11431
14    18           7269            4122              11391
67    76           3341            7508              10849

In [82]:
max_ano = max(df['ano'])

df_decada = df.loc[df['ano'] > max_ano - 10]

df_decada

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
22357,1,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,4.0,0.0,12,0,0,0,0,0,375,3
22358,4,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,1,...,19.0,1.0,20,2,1,0,0,0,630,3
22359,5,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,17.0,3.0,26,1,0,0,0,0,836,3
22360,6,1,2017,2017m01,4,1,Rio de Janeiro,3304557,Capital,1,...,11.0,0.0,18,2,0,0,0,0,482,3
22361,7,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,3,...,4.0,0.0,10,0,0,0,0,0,230,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [ ]:
df_furtos_ultima_decada = df_decada.groupby('regiao')[['total_furtos']].sum().reset_index()
df_furtos_ultima_decada

                          regiao  total_furtos
0             Baixada Fluminense        173968
1                        Capital        850475
2  Grande NiterÃÂÃÂÃÂÃÂ³i         98277
3                 Grande Niterói         22959
4                       Interior        234670

In [87]:
array_furtos_ultima_decada = np.array(df_furtos_ultima_decada[['total_furtos']])
q1_furtos_ultima_decada = np.percentile(array_furtos_ultima_decada, 25)
q2_furtos_ultima_decada = np.percentile(array_furtos_ultima_decada, 50)
q3_furtos_ultima_decada = np.percentile(array_furtos_ultima_decada, 75)
media_ocorrencia = np.mean(array_furtos_ultima_decada)
mediana_ocorrencia = np.median(array_furtos_ultima_decada)
distancia_ocorrencia = (media_ocorrencia - mediana_ocorrencia) / mediana_ocorrencia
iqr = q3_furto_celular - q1_furto_celular
limite_superior = q3_furto_celular + (1.5 * iqr)
limite_inferior = q1_furto_celular - (1.5 * iqr)

print(f'O limite superior é de {limite_superior}')
print(f'O limite inferior é de {limite_inferior}')

O limite superior é de 10773.125
O limite inferior é de -5741.875