In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('vendas_vestuario_revisao.csv')
df

   vendedor          produto  quantidade  valor_unitario
0   Edmundo    Camisa Social           2          217.87
1     Marta          Legging           2           76.57
2   Roberto      Calça Jeans           4          177.24
3   Roberto  Camiseta Básica           3           74.81
4    Junior          Legging           6          172.72
..      ...              ...         ...             ...
95  Roberto      Camisa Polo           3          145.74
96    Marta   Vestido Casual           2          207.33
97    Marta   Vestido Casual           4          236.13
98    Dulce    Jaqueta Jeans           4          384.26
99    Marta          Legging           4          114.32

[100 rows x 4 columns]

In [ ]:
df['Valor vendido'] = df['quantidade'] * df['valor_unitario'] # df['Valor vendido] Para criar nova coluna. Após = é o que alimenta
df

   vendedor          produto  quantidade  valor_unitario  Valor vendido
0   Edmundo    Camisa Social           2          217.87         435.74
1     Marta          Legging           2           76.57         153.14
2   Roberto      Calça Jeans           4          177.24         708.96
3   Roberto  Camiseta Básica           3           74.81         224.43
4    Junior          Legging           6          172.72        1036.32
..      ...              ...         ...             ...            ...
95  Roberto      Camisa Polo           3          145.74         437.22
96    Marta   Vestido Casual           2          207.33         414.66
97    Marta   Vestido Casual           4          236.13         944.52
98    Dulce    Jaqueta Jeans           4          384.26        1537.04
99    Marta          Legging           4          114.32         457.28

[100 rows x 5 columns]

In [ ]:
df_valor_vendido_vendedor = df.groupby('vendedor')['Valor vendido'].sum().reset_index() # reset.index() para que o 'vendedor' não seja o index
df_valor_vendido_vendedor

  vendedor  Valor vendido
0    Dulce       16849.41
1  Edmundo       10438.38
2   Junior       13575.26
3    Marta       17816.03
4  Roberto       11801.67